# Generated by Django 5.0.1 on 2024-02-02 12:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='countryes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='groupdeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='parentcountrypartyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='regions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='typeofdeals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='bin',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='codeOKPO',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='fullname',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='kbe',
            field=models.CharField(blank=True, max_length=2, null=True),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='numberofregistration',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='country',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.countryes'),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='parentcountryparty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.parentcountrypartyes'),
        ),
        migrations.AddField(
            model_name='countrypartyes',
            name='region',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.regions'),
        ),
        migrations.CreateModel(
            name='deals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('activityagreement', models.BooleanField(default=1)),
                ('VATagent', models.BooleanField(default=1)),
                ('countrypartyes', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.countrypartyes')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.organizations')),
                ('groupdeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.groupdeals')),
                ('typeofdeal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='appay.typeofdeals')),
            ],
        ),
    ]
