# Generated by Django 5.0.1 on 2024-02-03 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appay', '0002_countryes_groupdeals_parentcountrypartyes_regions_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RegPay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('model_pays', models.ManyToManyField(to='appay.modelpays')),
            ],
        ),
    ]
