# Generated by Django 5.0.1 on 2024-02-03 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appay', '0003_regpay'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='currencyes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('fullname', models.CharField(max_length=50)),
            ],
        ),
        migrations.AddField(
            model_name='regpay',
            name='amounOfPayment',
            field=models.CharField(default=2005, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpay',
            name='budgetItem',
            field=models.CharField(default=2005, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpay',
            name='contractNumber',
            field=models.CharField(default=2005, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpay',
            name='paymentDestination',
            field=models.CharField(default=2005, max_length=250),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpay',
            name='nameOfBank',
            field=models.ForeignKey(default=2005, on_delete=django.db.models.deletion.CASCADE, to='appay.banks'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='regpay',
            name='currency',
            field=models.ForeignKey(default=2005, on_delete=django.db.models.deletion.CASCADE, to='appay.currencyes'),
            preserve_default=False,
        ),
    ]
